### PR TITLE
Use encoding instead of iconv and allow objects with url property.

### PR DESCRIPTION
**Pull request by alexlangberg**
Hello!

Nice little crawler project. :)

I couldn't use this because iconv wouldn't work (easily) on my Debian machine. I suggest changing the iconv dependency to encoding which uses iconv-lite which is both faster and has better compatibility. One can still use iconv with encoding if you feel like.

I also added the option to pass in an object with a url property instead of just a string. This allows the user to pass properties along with the url object that can then later be used when the data is returned. Useful if you need to do something different for each url that has been scraped. I also wrote tests and corrected another test that was for some reason always passed, although it ought to fail.

What do you think? :)

### CODE REVIEW

**Comment by ondrs** [comment]
Hi,
thank you for the pull request!
I don't have any problem with replacing iconv with encoding and iconv-lite.

If you want to allow passing an object with a url property you should also check if the url property exists. If it does not you should throw an exception. 
Can you also update the readme file for this use case?

Why is Travis failing?

When you fix those issues I can merge it.
Thank you!

**Comment by alexlangberg** [comment]
Should all be fixed now. Travis failed because of some weird bug where npm has to be updated before dependencies work for node 0.8. :)

**Comment by ondrs** [comment]
I released v0.3.0 with merged features.
Happy crawling! :)

**Comment by alexlangberg** [comment]
Cool, thanks. You too. :)

**Pull request merged**
